version: '3'
services:
  rob-server:
    build:
      context: .
      dockerfile: env/Dockerfile
    ports:
      - "8000:8000/udp"
  rob-app:
    build:
      context: .
      dockerfile: app/Dockerfile
  rob-esp:
    build:
      context: .
      dockerfile: firmware/Dockerfile