version: '3'
services:
  robot-udp:
    build:
      context: server
      dockerfile: server/Dockerfile
    stdin_open: true
    tty: true
#    networks:
#      - robot-network
    ports:
      - "8000:8000/udp"  # Replace with the desired UDP port
#networks:
#  robot-network:
#    driver: bridge